/// Translation Editor — side-by-side EN reference vs. target language.
///
/// Shows all translation keys from the English reference TOML, lets the user
/// edit the target language values inline, and provides:
///   - Progress bar (translated / total keys)
///   - Filter: missing only, keyword search
///   - "Export .toml" for everyone
///   - "Commit & Push" for authenticated GitHub contributors
///   - "AI Translate" when an LLM role is configured in Service Roles
use std::fmt::Write as _;

use dioxus::prelude::*;
use fs_i18n;
use fs_manager_language::git_contributor::{ContributorStatus, GitContributorCheck};

use crate::service_roles::load_role_assignments;

// ── Reference TOML (compile-time) ─────────────────────────────────────────────

const EN_TOML: &str = include_str!("../assets/i18n/en.toml");

// ── TranslationEntry ──────────────────────────────────────────────────────────

#[derive(Clone, PartialEq, Debug)]
struct TranslationEntry {
    key: String,
    en_value: String,
    /// Current value in the target language (empty = untranslated).
    target_val: String,
    edited: bool,
}

impl TranslationEntry {
    fn is_translated(&self) -> bool {
        !self.target_val.is_empty()
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn flatten_toml(toml_str: &str) -> Vec<(String, String)> {
    let Ok(table) = toml_str.parse::<toml::Table>() else {
        return Vec::new();
    };
    let mut out = Vec::new();
    flatten_table(&table, "", &mut out);
    out
}

fn flatten_table(table: &toml::Table, prefix: &str, out: &mut Vec<(String, String)>) {
    for (k, v) in table {
        let full_key = if prefix.is_empty() {
            k.clone()
        } else {
            format!("{prefix}.{k}")
        };
        match v {
            toml::Value::String(s) => out.push((full_key, s.clone())),
            toml::Value::Table(t) => flatten_table(t, &full_key, out),
            other => out.push((full_key, other.to_string())),
        }
    }
}

fn entries_to_toml(entries: &[TranslationEntry]) -> String {
    let mut lines = vec![
        "# FreeSynergy translation".to_string(),
        "# Generated by Translation Editor".to_string(),
        String::new(),
    ];
    for e in entries {
        if e.is_translated() {
            let escaped = e.target_val.replace('\\', r"\\").replace('"', r#"\""#);
            lines.push(format!("{} = \"{}\"", e.key, escaped));
        }
    }
    lines.join("\n")
}

fn load_installed_translation(lang_code: &str) -> Vec<(String, String)> {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
    let path = std::path::PathBuf::from(home)
        .join(".local/share/fsn/i18n")
        .join(lang_code)
        .join("ui.toml");
    let content = std::fs::read_to_string(path).unwrap_or_default();
    flatten_toml(&content)
}

fn build_entries(lang_code: &str) -> Vec<TranslationEntry> {
    let en_pairs = flatten_toml(EN_TOML);
    let tgt_pairs = load_installed_translation(lang_code);
    let tgt_map: std::collections::HashMap<String, String> = tgt_pairs.into_iter().collect();

    en_pairs
        .into_iter()
        .map(|(key, en_value)| {
            let target_val = tgt_map.get(&key).cloned().unwrap_or_default();
            TranslationEntry {
                key,
                en_value,
                target_val,
                edited: false,
            }
        })
        .collect()
}

// ── LLM helpers ───────────────────────────────────────────────────────────────

/// Auto-generates the LLM prompt: EN reference + missing keys.
fn build_llm_prompt(
    lang_name: &str,
    lang_code: &str,
    entries: &[TranslationEntry],
    user_request: &str,
) -> String {
    let missing: Vec<&TranslationEntry> = entries
        .iter()
        .filter(|e| !e.is_translated())
        .take(50)   // Limit to avoid token overflow
        .collect();

    let mut prompt = format!(
        "You are a professional software translator for the FreeSynergy open-source project.\n\
         Translate the following UI text strings into {lang_name} ({lang_code} locale).\n\
         Return ONLY a flat TOML block — one line per key, format: \"key.name\" = \"translation\"\n\
         No explanations, no code fences, no comments.\n\n\
         Strings to translate:\n"
    );

    for e in &missing {
        let escaped = e.en_value.replace('"', r#"\""#);
        let _ = writeln!(prompt, "\"{}\" = \"{}\"", e.key, escaped);
    }

    if !user_request.trim().is_empty() {
        let _ = write!(prompt, "\nAdditional instruction: {}", user_request.trim());
    }

    prompt
}

/// Parses the LLM response into `(key, value)` proposal pairs.
fn parse_llm_proposals(response: &str) -> Vec<(String, String)> {
    let mut proposals = Vec::new();

    // Strip markdown code fences if present
    let body = response
        .trim()
        .trim_start_matches("```toml")
        .trim_start_matches("```")
        .trim_end_matches("```")
        .trim();

    for line in body.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        // Match:  "key.subkey" = "value"  or  key.subkey = "value"
        if let Some(eq_pos) = line.find(" = \"") {
            let raw_key = line[..eq_pos].trim().trim_matches('"').to_string();
            let value_start = eq_pos + 4;
            if value_start < line.len() {
                let tail = &line[value_start..];
                let value = tail.trim_end_matches('"').to_string();
                if !raw_key.is_empty() {
                    proposals.push((raw_key, value));
                }
            }
        }
    }

    proposals
}

/// Calls the configured LLM service and returns the raw text response.
async fn call_llm_service(service_name: &str, prompt: String) -> Result<String, String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(120))
        .build()
        .map_err(|e| e.to_string())?;

    if service_name == "ollama" {
        let resp = client
            .post("http://localhost:11434/api/generate")
            .json(&serde_json::json!({
                "model": "llama3.2",
                "prompt": prompt,
                "stream": false
            }))
            .send()
            .await
            .map_err(|e| e.to_string())?;

        let json: serde_json::Value = resp.json().await.map_err(|e| e.to_string())?;
        json["response"]
            .as_str()
            .map(std::string::ToString::to_string)
            .ok_or_else(|| "Unexpected Ollama response format".to_string())
    } else {
        // Generic OpenAI-compatible API (llama.cpp server, LM Studio, etc.)
        let resp = client
            .post("http://localhost:8080/v1/chat/completions")
            .json(&serde_json::json!({
                "messages": [{ "role": "user", "content": prompt }],
                "stream": false
            }))
            .send()
            .await
            .map_err(|e| e.to_string())?;

        let json: serde_json::Value = resp.json().await.map_err(|e| e.to_string())?;
        json["choices"][0]["message"]["content"]
            .as_str()
            .map(std::string::ToString::to_string)
            .ok_or_else(|| "Unexpected API response format".to_string())
    }
}

// ── TranslationEditor ─────────────────────────────────────────────────────────

#[component]
pub fn TranslationEditor(
    lang_code: String,
    lang_name: String,
    on_close: EventHandler<()>,
) -> Element {
    let entries = use_signal(|| build_entries(&lang_code));
    let mut filter_empty = use_signal(|| false);
    let mut search_query = use_signal(String::new);

    // Git contributor status
    let contrib =
        use_signal(|| GitContributorCheck::cached().unwrap_or(ContributorStatus::Unknown));
    {
        let mut contrib = contrib;
        use_future(move || async move {
            if *contrib.read() == ContributorStatus::Unknown {
                let result = GitContributorCheck::check_and_cache();
                contrib.set(result);
            }
        });
    }

    // LLM: check if an "llm" service role is configured
    let role_cfg = load_role_assignments();
    let llm_service = role_cfg.get("llm").map(std::string::ToString::to_string);
    let llm_available = llm_service.is_some();
    let llm_service_name = llm_service.unwrap_or_default();

    // LLM panel state
    let mut show_llm_panel = use_signal(|| false);
    let mut llm_request = use_signal(String::new);
    let llm_busy = use_signal(|| false);
    let llm_proposals: Signal<Vec<(String, String)>> = use_signal(Vec::new);
    let llm_error = use_signal(|| Option::<String>::None);

    // Push state
    let push_msg = use_signal(|| Option::<Result<String, String>>::None);

    // Derived counts
    let total = entries.read().len();
    let translated = entries.read().iter().filter(|e| e.is_translated()).count();
    let pct = if total > 0 {
        (translated * 100) / total
    } else {
        0
    };

    // Filtered entries
    let query = search_query.read().to_lowercase();
    let show_empty = *filter_empty.read();
    let visible: Vec<(usize, TranslationEntry)> = entries
        .read()
        .iter()
        .enumerate()
        .filter(|(_, e)| {
            let matches_filter = !show_empty || !e.is_translated();
            let matches_search = query.is_empty()
                || e.key.to_lowercase().contains(&query)
                || e.en_value.to_lowercase().contains(&query);
            matches_filter && matches_search
        })
        .map(|(i, e)| (i, e.clone()))
        .collect();

    rsx! {
        div {
            style: "display: flex; flex-direction: column; height: 100%; \
                    background: var(--fs-color-bg-default);",

            // ── Header ────────────────────────────────────────────────────────
            div {
                style: "padding: 16px 20px; \
                        border-bottom: 1px solid var(--fs-color-border-default); \
                        display: flex; align-items: center; gap: 12px; flex-shrink: 0;",

                button {
                    style: "background: none; border: none; cursor: pointer; \
                            font-size: 18px; color: var(--fs-color-text-muted); padding: 0;",
                    onclick: move |_| on_close.call(()),
                    "←"
                }
                div { style: "flex: 1;",
                    h3 {
                        style: "margin: 0; font-size: 15px;",
                        {fs_i18n::t("settings.language.editor.title")}
                        span {
                            style: "margin-left: 8px; font-size: 13px; \
                                    color: var(--fs-color-primary); font-weight: 400;",
                            "{lang_name} ({lang_code})"
                        }
                    }
                }

                // Git contributor badge
                {
                    let (badge_label, badge_style) = match contrib.read().clone() {
                        ContributorStatus::Authenticated { github_user } => (
                            format!("GitHub: {github_user}"),
                            "background: rgba(34,197,94,0.15); color: #16a34a; \
                             border: 1px solid rgba(34,197,94,0.4);",
                        ),
                        ContributorStatus::NotAuthenticated => (
                            fs_i18n::t("settings.language.editor.no_ssh").into(),
                            "background: rgba(156,163,175,0.15); color: var(--fs-color-text-muted); \
                             border: 1px solid var(--fs-color-border-default);",
                        ),
                        ContributorStatus::Unknown => (
                            fs_i18n::t("settings.language.editor.checking_ssh").into(),
                            "background: rgba(234,179,8,0.15); color: #ca8a04; \
                             border: 1px solid rgba(234,179,8,0.4);",
                        ),
                    };
                    rsx! {
                        span {
                            style: "font-size: 11px; padding: 3px 10px; \
                                    border-radius: 999px; white-space: nowrap; {badge_style}",
                            "{badge_label}"
                        }
                    }
                }
            }

            // ── Progress bar ──────────────────────────────────────────────────
            div {
                style: "padding: 12px 20px; \
                        border-bottom: 1px solid var(--fs-color-border-default); flex-shrink: 0;",
                div {
                    style: "display: flex; justify-content: space-between; \
                            font-size: 12px; color: var(--fs-color-text-muted); margin-bottom: 6px;",
                    span { {fs_i18n::t_with("settings.language.editor.progress",
                                &[("done",  &translated.to_string()),
                                  ("total", &total.to_string())])} }
                    span { "{pct}%" }
                }
                div {
                    style: "height: 6px; background: var(--fs-color-bg-surface); \
                            border-radius: 999px; overflow: hidden;",
                    div {
                        style: "height: 100%; width: {pct}%; \
                                background: var(--fs-color-primary); \
                                border-radius: 999px; transition: width 0.3s;",
                    }
                }
            }

            // ── Toolbar ───────────────────────────────────────────────────────
            div {
                style: "padding: 10px 20px; display: flex; gap: 10px; align-items: center; \
                        border-bottom: 1px solid var(--fs-color-border-default); flex-shrink: 0;",

                // Search
                input {
                    style: "flex: 1; padding: 6px 10px; font-size: 13px; \
                            background: var(--fs-color-bg-surface); \
                            border: 1px solid var(--fs-color-border-default); \
                            border-radius: var(--fs-radius-sm); \
                            color: var(--fs-color-text-primary);",
                    r#type: "text",
                    placeholder: fs_i18n::t("settings.language.editor.search_placeholder").to_string(),
                    value: "{search_query}",
                    oninput: move |e| search_query.set(e.value()),
                }

                // Filter: missing only
                label {
                    style: "display: flex; align-items: center; gap: 6px; \
                            font-size: 12px; cursor: pointer; white-space: nowrap; \
                            color: var(--fs-color-text-muted);",
                    input {
                        r#type: "checkbox",
                        checked: *filter_empty.read(),
                        onchange: move |_| {
                            let cur = *filter_empty.read();
                            filter_empty.set(!cur);
                        },
                    }
                    {fs_i18n::t("settings.language.editor.show_missing")}
                }

                // Visible count
                span {
                    style: "font-size: 11px; color: var(--fs-color-text-muted);",
                    {fs_i18n::t_with("settings.language.editor.showing",
                        &[("n", &visible.len().to_string())])}
                }

                // AI Translate button — only when an LLM role is configured
                if llm_available {
                    button {
                        style: format!(
                            "padding: 6px 14px; font-size: 12px; border-radius: var(--fs-radius-sm); \
                             cursor: pointer; white-space: nowrap; font-weight: 500; \
                             border: 1px solid {}; background: {}; color: {};",
                            if *show_llm_panel.read() { "var(--fs-color-primary)" } else { "var(--fs-color-border-default)" },
                            if *show_llm_panel.read() { "rgba(77,139,245,0.15)" } else { "var(--fs-color-bg-surface)" },
                            if *show_llm_panel.read() { "var(--fs-color-primary)" } else { "var(--fs-color-text-primary)" },
                        ),
                        onclick: move |_| {
                            let cur = *show_llm_panel.read();
                            show_llm_panel.set(!cur);
                        },
                        "🤖 "
                        {fs_i18n::t("settings.language.editor.ai_translate")}
                    }
                }
            }

            // ── LLM Panel (collapsible) ────────────────────────────────────────
            if *show_llm_panel.read() && llm_available {
                div {
                    style: "padding: 16px 20px; flex-shrink: 0; \
                            border-bottom: 1px solid var(--fs-color-border-default); \
                            background: var(--fs-color-bg-surface);",

                    // Panel header
                    div {
                        style: "display: flex; align-items: center; gap: 8px; margin-bottom: 12px;",
                        span { style: "font-size: 13px; font-weight: 600;",
                            "🤖 "
                            {fs_i18n::t("settings.language.editor.ai_panel_title")}
                        }
                        span {
                            style: "font-size: 11px; color: var(--fs-color-text-muted); flex: 1;",
                            {fs_i18n::t("settings.language.editor.ai_prompt_hint")}
                        }
                        // Proposal count badge
                        if !llm_proposals.read().is_empty() {
                            span {
                                style: "font-size: 11px; padding: 2px 8px; border-radius: 999px; \
                                        background: rgba(77,139,245,0.15); \
                                        color: var(--fs-color-primary); font-weight: 500;",
                                {fs_i18n::t_with("settings.language.editor.ai_proposals",
                                    &[("n", &llm_proposals.read().len().to_string())])}
                            }
                        }
                    }

                    // Request textarea + Send button
                    div { style: "display: flex; gap: 8px; align-items: flex-end; margin-bottom: 12px;",
                        textarea {
                            style: "flex: 1; padding: 8px 10px; font-size: 13px; \
                                    background: var(--fs-color-bg-input, var(--fs-color-bg-default)); \
                                    border: 1px solid var(--fs-color-border-default); \
                                    border-radius: var(--fs-radius-sm); \
                                    color: var(--fs-color-text-primary); resize: vertical; \
                                    min-height: 60px; font-family: inherit;",
                            placeholder: "e.g. Translate all missing keys, keep technical terms in English",
                            value: "{llm_request}",
                            oninput: move |e| llm_request.set(e.value()),
                        }
                        button {
                            style: format!(
                                "padding: 8px 18px; background: var(--fs-color-primary); \
                                 color: white; border: none; \
                                 border-radius: var(--fs-radius-sm); font-size: 13px; \
                                 cursor: pointer; white-space: nowrap; height: fit-content; \
                                 opacity: {};",
                                if *llm_busy.read() { "0.6" } else { "1" }
                            ),
                            disabled: *llm_busy.read(),
                            onclick: {
                                let lang_name2     = lang_name.clone();
                                let lang_code2     = lang_code.clone();
                                let llm_request    = llm_request;
                                let llm_service    = llm_service_name.clone();
                                let mut llm_busy   = llm_busy;
                                let mut llm_proposals = llm_proposals;
                                let mut llm_error  = llm_error;
                                move |_| {
                                    let prompt = build_llm_prompt(
                                        &lang_name2,
                                        &lang_code2,
                                        &entries.read(),
                                        &llm_request.read(),
                                    );
                                    let service = llm_service.clone();
                                    llm_busy.set(true);
                                    llm_proposals.set(Vec::new());
                                    llm_error.set(None);
                                    let mut llm_busy2    = llm_busy;
                                    let mut llm_proposals2 = llm_proposals;
                                    let mut llm_error2   = llm_error;
                                    spawn(async move {
                                        match call_llm_service(&service, prompt).await {
                                            Ok(response) => {
                                                let proposals = parse_llm_proposals(&response);
                                                if proposals.is_empty() {
                                                    llm_error2.set(Some(
                                                        fs_i18n::t("settings.language.editor.ai_no_proposals").into()
                                                    ));
                                                } else {
                                                    llm_proposals2.set(proposals);
                                                }
                                            }
                                            Err(e) => {
                                                llm_error2.set(Some(
                                                    fs_i18n::t_with(
                                                        "settings.language.editor.ai_error",
                                                        &[("msg", &e)],
                                                    ).into()
                                                ));
                                            }
                                        }
                                        llm_busy2.set(false);
                                    });
                                }
                            },
                            if *llm_busy.read() {
                                {fs_i18n::t("settings.language.editor.ai_thinking")}
                            } else {
                                {fs_i18n::t("settings.language.editor.ai_send")}
                            }
                        }
                    }

                    // Error message
                    if let Some(err) = llm_error.read().as_ref() {
                        div {
                            style: "font-size: 12px; color: var(--fs-color-error, #f87171); \
                                    margin-bottom: 8px;",
                            "{err}"
                        }
                    }

                    // Proposals list
                    if !llm_proposals.read().is_empty() {
                        div {
                            // Accept All bar
                            div {
                                style: "display: flex; align-items: center; justify-content: flex-end; \
                                        margin-bottom: 8px;",
                                button {
                                    style: "padding: 5px 14px; font-size: 12px; \
                                            background: var(--fs-color-primary); color: white; \
                                            border: none; border-radius: var(--fs-radius-sm); \
                                            cursor: pointer;",
                                    onclick: {
                                        let mut entries       = entries;
                                        let mut llm_proposals = llm_proposals;
                                        move |_| {
                                            let proposals = llm_proposals.read().clone();
                                            for (key, value) in &proposals {
                                                let idx = { entries.read().iter().position(|e| &e.key == key) };
                                                if let Some(i) = idx {
                                                    entries.write()[i].target_val.clone_from(value);
                                                    entries.write()[i].edited     = true;
                                                }
                                            }
                                            llm_proposals.set(Vec::new());
                                        }
                                    },
                                    {fs_i18n::t("settings.language.editor.ai_accept_all")}
                                }
                            }

                            // Individual proposals
                            div {
                                style: "border: 1px solid var(--fs-color-border-default); \
                                        border-radius: var(--fs-radius-md); overflow: hidden; \
                                        max-height: 240px; overflow-y: auto; scrollbar-width: thin;",

                                for proposal in llm_proposals.read().clone().into_iter().enumerate() {
                                    {
                                        let (idx, (key, value)): (usize, (String, String)) = proposal;
                                        rsx! {
                                            div {
                                                key: "{idx}",
                                                style: "display: grid; grid-template-columns: 160px 1fr auto; \
                                                        gap: 0; padding: 0; \
                                                        border-bottom: 1px solid var(--fs-color-border-default);",

                                                // Key
                                                div {
                                                    style: "padding: 8px 12px; font-size: 11px; \
                                                            font-family: monospace; \
                                                            color: var(--fs-color-text-muted); \
                                                            border-right: 1px solid var(--fs-color-border-default); \
                                                            display: flex; align-items: center; \
                                                            word-break: break-all;",
                                                    "{key}"
                                                }

                                                // Proposed value
                                                div {
                                                    style: "padding: 8px 12px; font-size: 13px; \
                                                            color: var(--fs-color-text-primary); \
                                                            border-right: 1px solid var(--fs-color-border-default); \
                                                            display: flex; align-items: center;",
                                                    "{value}"
                                                }

                                                // Accept button
                                                div {
                                                    style: "padding: 6px 12px; display: flex; \
                                                            align-items: center;",
                                                    button {
                                                        style: "padding: 3px 10px; font-size: 12px; \
                                                                background: rgba(34,197,94,0.15); \
                                                                color: #16a34a; \
                                                                border: 1px solid rgba(34,197,94,0.4); \
                                                                border-radius: var(--fs-radius-sm); \
                                                                cursor: pointer;",
                                                        onclick: {
                                                            let key2   = key.clone();
                                                            let value2 = value.clone();
                                                            let mut entries       = entries;
                                                            let mut llm_proposals = llm_proposals;
                                                            move |_| {
                                                                let idx = { entries.read().iter().position(|e| e.key == key2) };
                                                                if let Some(i) = idx {
                                                                    entries.write()[i].target_val.clone_from(&value2);
                                                                    entries.write()[i].edited     = true;
                                                                }
                                                                llm_proposals.write().retain(|(k, _)| k != &key2);
                                                            }
                                                        },
                                                        "✓"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // ── Key list ──────────────────────────────────────────────────────
            div {
                style: "flex: 1; overflow-y: auto; scrollbar-width: thin;",

                // Column header
                div {
                    style: "display: grid; grid-template-columns: 200px 1fr 1fr; \
                            gap: 0; padding: 8px 20px; \
                            background: var(--fs-color-bg-surface); \
                            border-bottom: 1px solid var(--fs-color-border-default); \
                            font-size: 11px; font-weight: 600; \
                            color: var(--fs-color-text-muted); text-transform: uppercase; \
                            letter-spacing: 0.05em; position: sticky; top: 0; z-index: 1;",
                    span { {fs_i18n::t("settings.language.editor.col_key")} }
                    span { "English" }
                    span { "{lang_name}" }
                }

                for (idx, entry) in visible {
                    TranslationRow {
                        key: "{idx}",
                        entry: entry.clone(),
                        on_change: {
                            let mut entries = entries;
                            move |new_val: String| {
                                entries.write()[idx].target_val = new_val;
                                entries.write()[idx].edited     = true;
                            }
                        },
                    }
                }
            }

            // ── Action bar ────────────────────────────────────────────────────
            div {
                style: "padding: 14px 20px; border-top: 1px solid var(--fs-color-border-default); \
                        display: flex; align-items: center; gap: 12px; flex-shrink: 0;",

                // Export .toml
                button {
                    style: "padding: 8px 18px; background: var(--fs-color-bg-surface); \
                            border: 1px solid var(--fs-color-border-default); \
                            border-radius: var(--fs-radius-md); font-size: 13px; \
                            cursor: pointer; color: var(--fs-color-text-primary);",
                    onclick: {
                        let lang_code = lang_code.clone();
                        move |_| {
                            let toml_str = entries_to_toml(&entries.read());
                            let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
                            let dest = std::path::PathBuf::from(&home)
                                .join("Downloads")
                                .join(format!("fs-{lang_code}.toml"));
                            let _ = std::fs::create_dir_all(dest.parent().unwrap());
                            let _ = std::fs::write(&dest, &toml_str);
                            let install_dir = std::path::PathBuf::from(&home)
                                .join(".local/share/fsn/i18n")
                                .join(&lang_code);
                            let _ = std::fs::create_dir_all(&install_dir);
                            let _ = std::fs::write(install_dir.join("ui.toml"), toml_str);
                        }
                    },
                    {fs_i18n::t("settings.language.editor.btn_export")}
                }

                // Push to GitHub (contributor only)
                if let ContributorStatus::Authenticated { .. } = contrib.read().clone() {
                    button {
                        style: "padding: 8px 18px; background: var(--fs-color-primary); \
                                color: white; border: none; \
                                border-radius: var(--fs-radius-md); font-size: 13px; \
                                cursor: pointer;",
                        onclick: {
                            let lang_code = lang_code.clone();
                            move |_| {
                                let toml_str  = entries_to_toml(&entries.read());
                                let lang_code = lang_code.clone();
                                let mut push_msg = push_msg;
                                spawn(async move {
                                    let repo_path = std::env::var("FS_NODE_REPO_PATH")
                                        .unwrap_or_else(|_| {
                                            let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
                                            format!("{home}/FreeSynergy.Node")
                                        });
                                    let result = fs_manager_language::git_contributor::GitContributorCheck
                                        ::push_translation(
                                            std::path::Path::new(&repo_path),
                                            &lang_code,
                                            &toml_str,
                                        );
                                    push_msg.set(Some(result));
                                });
                            }
                        },
                        {fs_i18n::t("settings.language.editor.btn_push")}
                    }
                }

                // Re-check SSH
                button {
                    style: "padding: 8px 12px; background: none; border: none; \
                            font-size: 12px; color: var(--fs-color-text-muted); \
                            cursor: pointer; text-decoration: underline;",
                    onclick: {
                        let mut contrib = contrib;
                        move |_| {
                            GitContributorCheck::clear_cache();
                            contrib.set(ContributorStatus::Unknown);
                        }
                    },
                    {fs_i18n::t("settings.language.editor.btn_recheck_ssh")}
                }

                // Push result message
                if let Some(result) = push_msg.read().as_ref() {
                    span {
                        style: {
                            let color = if result.is_ok() { "var(--fs-color-success, #16a34a)" }
                                        else              { "var(--fs-color-error, #dc2626)" };
                            format!("font-size: 12px; color: {color};")
                        },
                        {
                            match result {
                                Ok(msg)  => msg.clone(),
                                Err(err) => format!("Error: {err}"),
                            }
                        }
                    }
                }
            }
        }
    }
}

// ── TranslationRow ────────────────────────────────────────────────────────────

#[component]
fn TranslationRow(entry: TranslationEntry, on_change: EventHandler<String>) -> Element {
    let row_bg = if entry.edited {
        "background: rgba(234,179,8,0.06);"
    } else if !entry.is_translated() {
        "background: rgba(220,38,38,0.04);"
    } else {
        "background: transparent;"
    };

    rsx! {
        div {
            style: "display: grid; grid-template-columns: 200px 1fr 1fr; \
                    gap: 0; padding: 0; \
                    border-bottom: 1px solid var(--fs-color-border-default); \
                    {row_bg}",

            // Key column
            div {
                style: "padding: 8px 20px; font-size: 11px; font-family: monospace; \
                        color: var(--fs-color-text-muted); word-break: break-all; \
                        border-right: 1px solid var(--fs-color-border-default); \
                        display: flex; align-items: center;",
                span { "{entry.key}" }
            }

            // English reference (read-only)
            div {
                style: "padding: 8px 12px; font-size: 13px; \
                        color: var(--fs-color-text-secondary, var(--fs-color-text-muted)); \
                        border-right: 1px solid var(--fs-color-border-default); \
                        display: flex; align-items: center;",
                span { "{entry.en_value}" }
            }

            // Target language (editable)
            div {
                style: "padding: 4px 8px; display: flex; align-items: center;",
                textarea {
                    style: "width: 100%; min-height: 32px; padding: 4px 6px; \
                            font-size: 13px; font-family: inherit; \
                            background: transparent; resize: none; \
                            border: 1px solid transparent; \
                            border-radius: var(--fs-radius-sm); \
                            color: var(--fs-color-text-primary); \
                            transition: border-color 0.1s;",
                    rows: "1",
                    placeholder: "…",
                    value: "{entry.target_val}",
                    oninput: move |e| on_change.call(e.value()),
                    onfocus: move |e: FocusEvent| { let _ = e; },
                }
            }
        }
    }
}
