pub mod ai_view;
pub mod app_shell;
pub mod spinner;
pub mod widgets;
pub mod desktop;
pub mod header;
pub mod help_view;
pub mod launcher;
pub mod multiwindow;
pub mod notification;
pub mod sidebar;
pub mod split_view;
pub mod taskbar;
pub mod wallpaper;
pub mod web_desktop;
pub mod window;
pub mod window_frame;

pub use ai_view::AiApp;
pub use app_shell::{AppMode, AppShell, LayoutA, LayoutB, LayoutC, ScreenWrapper};
pub use desktop::Desktop;
pub use header::{Breadcrumb, ShellHeader};
pub use help_view::HelpApp;
pub use launcher::{AppLauncher, LauncherState};
pub use multiwindow::{MultiwindowHandle, use_multiwindow};
pub use notification::{Notification, NotificationKind, NotificationManager, NotificationStack};
pub use sidebar::{ShellSidebar, SidebarSection, SidebarNavItem};
pub use split_view::{SplitState, SplitView};
pub use taskbar::Taskbar;
pub use web_desktop::{WebDesktop, WebTaskbarState};
pub use window::{Window, WindowButton, WindowContent, WindowId, WindowManager, WindowSize};
pub use window_frame::WindowFrame;
pub use spinner::{LoadingOverlay, LoadingSpinner, SpinnerSize};
pub use widgets::{ClockWidget, SystemInfoWidget};
